on: [push]
name: Conda build

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
    - name: Build
      id: build
      uses: sot/skare3/actions/build@gh-actions
      with:
        package: 'Quaternion'
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        GIT_ASKPASS: /home/aca/git_pass.py
    - uses: sot/skare3/actions/gdrive_upload@gh-actions
      name: Upload to Google Drive
      id: upload
      with:
        files: builds/linux-64 builds/noarch
        directory: ska-ci/conda-test
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}


  build-macos:
    runs-on: macos-latest
    name: Build on Mac OS
    steps:
    - name: Fetch Skare3
      uses: actions/checkout@v2
      with:
        repository: sot/skare3
        ref: gh-actions
        path: skare3
    - name: Build
      run: |
        sed -e "s/\${CONDA_PASSWORD}/${CONDA_PASSWORD}/g" ./skare3/actions/build/files/condarc > $HOME/.condarc
        curl -O https://repo.continuum.io/miniconda/Miniconda3-4.3.21-MacOSX-x86_64.sh
        bash Miniconda3-4.3.21-MacOSX-x86_64.sh -b
        export PATH=${HOME}/miniconda3/bin:$PATH
        conda install python=3.6.2 conda=4.3.21 -q --yes
        conda install ska3_builder -q --yes
        cd skare3
        ./ska_builder.py --tag master --force Quaternion
        ls -R builds
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_ASKPASS: skare3/actions/build/files/git_pass.py
        GIT_USER: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}


  Build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
    - name: Fetch Skare3
      uses: actions/checkout@v2
      with:
        repository: sot/skare3
        ref: gh-actions
        path: skare3
    - name: Build
      run: |
        dir