on: [push]
name: Conda build

jobs:


  build-macos:
    runs-on: macos-latest
    name: Build on Mac OS
    steps:
    - name: Fetch Skare3
      uses: actions/checkout@v2
      with:
        repository: sot/skare3
        ref: gh-actions
        path: skare3
    - name: Build
      run: |
        source ./skare3/actions/build/files/setup_conda.sh
        source ./skare3/actions/build/files/build.sh ${GITHUB_REPOSITORY}
      env:
        CONDA_PASSWORD: ${{ secrets.CONDA_PASSWORD }}
        GIT_ASKPASS: skare3/actions/build/files/git_pass.py
        GIT_USER: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
    - name: Upload to Google Drive
      run: |
        echo ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }} > ${HOME}/gdrive_credentials.json
        pip3 install --user google-api-python-client
        ./skare3/actions/gdrive_upload/gdrive.py upload builds/osx-64 builds/noarch ska-ci/conda-test


  build-windows:
    runs-on: windows-latest
    name: Build on Windows
    steps:
    - name: Fetch Skare3
      uses: actions/checkout@v2
      with:
        repository: sot/skare3
        ref: gh-actions
        path: skare3
    - name: Build
      run: |
        dir