on: [push]

jobs:
  build-package:
    runs-on: ubuntu-latest
    name: Package building
    steps:
    - name: setup
      run: |
        echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}" > gdrive_credentials.json
        chmod 600 gdrive_credentials.json
    - name: build
      id: build
      uses: sot/skare3/actions/build@gh-actions
      with:
        package: 'Quaternion'
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        GIT_ASKPASS: /home/aca/git_pass.py
    - name: results
      run: echo "${{ steps.build.outputs.files }}"
