on: [push]

jobs:
  build-package:
    runs-on: ubuntu-latest
    name: Conda Package (Linux)
    steps:
    - name: build
      id: build
      uses: sot/skare3/actions/build@gh-actions
      with:
        package: 'Quaternion'
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        GIT_ASKPASS: /home/aca/git_pass.py
    - uses: sot/skare3/actions/gdrive_upload@gh-actions
      name: upload
      id: upload
      with:
        files: builds/linux-64 builds/noarch
        directory: ska-ci/conda-test
      env:
        GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
